const darkTheme = {
  colors: {
    primary: "#0070f344",
    danger: "#ff5555",
    bg: "#111",
    fg: "#fff",
    card_border: "#eaeaea33",
    button_border: "#ffffff99",
    nav_bg: "#aaaaaa11",
    description: "#aaaaaaff",
    product_title: "#bbbbbb",
    card_hover_border: "#0ff",
    nav_count_fg: "#fff",
    nav_count_bg: "#aaaaaa33",
    cart_table_head_fg: "#aaaaaa88",
    delete_icon: "#f00",
    checkbox_unchecked_hover_bg: "#aaa",
    checkbox_unchecked_bg: "#777",
    cart_border: "#fafafa11",
    select_item_hover: "#77777777",
  },
};
const lightTheme = {
  colors: {
    primary: "#0070f366",
    danger: "#ff5555",
    bg: "#eaeaea",
    fg: "#000",
    card_border: "#bebebe99",
    button_border: "#11111999",
    nav_bg: "#fff",
    description: "#111111ff",
    product_title: "#777777",
    card_hover_border: "#00f",
    nav_count_fg: "#111",
    nav_count_bg: "#44444444",
    cart_table_head_fg: "#777",
    delete_icon: "#f00",
    checkbox_unchecked_hover_bg: "#888",
    checkbox_unchecked_bg: "#aaa",
    cart_border: "#0a0a0a22",
    select_item_hover: "#aaaaaaaa",
  },
};

export { darkTheme, lightTheme };
